<?php View::notify(); ?>

<script type="text/javascript">  
    $(function() {
        $('table').dwGrid({             
            order_attr: '<?= (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"sistema/sucursal/listar/"
        });
    });    
</script>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <div class="btn-toolbar btn-toolbar-top">        
        <div class="btn-actions">            
            <?= DwHtml::button("sistema/sucursal/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?> 
        </div>
    </div>
    
    <div class="dw-overflow">
    
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">        
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="direccion">DIRECCION</th>
                    <th class="col-collapse" data-search="ciudad">CIUDAD</th>
                    <th class="col-collapse" data-search="celular">CELULAR</th>
                    <th class="col-collapse" data-search="telefono">TELEFONO</th>
                    <th class="col-collapse" data-search="fax">FAX</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>            
            </thead>
            <tbody>            
                <?php foreach($sucursales->items as $sucursal): ?>
                    <?php $key_upd = DwSecurity::getKey($sucursal->id, 'upd_sucursal'); ?> 
                    <?php $key_del = DwSecurity::getKey($sucursal->id, 'del_sucursal'); ?> 
                    <tr>
                        <td><?= $sucursales->counter; ?></td>
                        <td><?= $sucursal->sucursal; ?></td>
                        <td><?= $sucursal->direccion; ?></td>
                        <td><?= $sucursal->ciudad; ?></td>
                        <td><?= $sucursal->celular; ?></td>
                        <td><?= $sucursal->telefono; ?></td>
                        <td><?= $sucursal->fax; ?></td>
                        <td>
                            <?= DwHtml::buttonTable('Modificar sucursal', "sistema/sucursal/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?= DwHtml::buttonTable('Eliminar sucursal', "sistema/sucursal/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar sucursal', 'confirm-body'=>'Está seguro de eliminar esta sucursal? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $sucursal->counter++; ?>
                <?php endforeach; ?>
            </tbody>            
        </table> 
        
    </div>
    
    <?php View::partial('paginators/default', false, array('page'=>$sucursales, 'url'=>"sistema/sucursal/listar/$order/")); ?>
    
</div>