<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>sistema/backup/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"sistema/backup/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("sistema/backup/crear/", 'crear', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="fecha">FECHA</th>
                    <th class="col-collapse">HORA</th>
                    <th class="col-collapse" data-search="denominacion">DENOMINACION</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="apellido">APELLIDO</th>
                    <th class="col-collapse no-form-search" data-search="tamano">TAMAÑO</th>
                    <th class="col-collapse">ARCHIVO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($backups->items as $backup): ?>
                    <?php $key_res = DwSecurity::getKey($backup->id, 'restaurar_backup'); ?>
                    <?php $key_dwn = DwSecurity::getKey($backup->id, 'descargar_backup'); ?>
                    <tr data-backup-description="<?php echo $backup->denominacion; ?>" data-backup-file="<?php echo $backup->archivo; ?>" data-backup-datetime="<?php echo $backup->registrado_at; ?>">
                        <td><?php echo $backups->counter; ?></td>
                        <td><?php echo date("Y-m-d", strtotime($backup->registrado_at)); ?></td>
                        <td><?php echo date("H:i:s", strtotime($backup->registrado_at)); ?></td>
                        <td><?php echo $backup->denominacion; ?></td>
                        <td><?php echo $backup->nombre; ?></td>
                        <td><?php echo $backup->apellido; ?></td>
                        <td><?php echo $backup->tamano; ?></td>
                        <td><?php echo $backup->archivo; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Restarurar sistema', "sistema/backup/restaurar/$key_res/", array('class'=>'js-confirm', 'confirm-title'=>'Restaurar sistema', 'confirm-body'=>'Está seguro de querer restaurar el sistema con esta copia de seguridad?', 'on-confirm'=>'backupRestore'), 'danger', 'warning-sign'); ?>
                            <?php echo DwHtml::buttonTable('Descargar backup', "sistema/backup/descargar/$key_dwn/", array('class'=>'no-ajax', 'target'=>'_blank'), 'info', 'download-alt'); ?>
                        </td>
                    </tr>
                    <?php $backups->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$backups, 'url'=>"sistema/backup/listar/$order/")); ?>

</div>

    <div class="modal hide" id="form-add-bakcup">
        <?php echo DwForm::open("", '', array('id'=>'form-modal', 'class'=>'dw-validate js-remote', 'data-to'=>'dw-message')); ?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3>Restauración del sistema</h3>
                <div id="dw-backup-info" style="margin-top: 20px">

                </div>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="span5">
                        <?php echo DwForm::pass('password', array('class'=>'input-required show-errors'), '', 'Contraseña'); ?>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
                <?php echo DwForm::submit("Restaurar", array('class'=>'btn btn-primary')); ?>
            </div>
        <?php echo DwForm::close(); ?>
    </div>

<script type="text/javascript">
    function backupRestore(refer) {
        $("#form-modal").attr('action', refer.attr('href'));
        $("#password").val('');
        var backup_info = refer.parents('tr:first');
        $("#dw-backup-info").empty();
        $("#dw-backup-info").append('<h5 style="margin: 3px 0px">Fecha: '+backup_info.attr('data-backup-datetime')+'</h5>');
        $("#dw-backup-info").append('<h5 style="margin: 3px 0px">Archivo: '+backup_info.attr('data-backup-file')+'</h5>');
        $("#dw-backup-info").append('<h5 style="margin: 3px 0px">Denominación: '+backup_info.attr('data-backup-description')+'</h5>');
        $('#form-add-bakcup').modal('show')
    }
    $(function(){
        $("#form-modal").on('submit', function() {
            $("#dw-message").empty();
            DwMessage('Restaurando el sistema...<br />Esta operación puede demorar unos minutos.', 'info');
            $('#form-add-bakcup').modal('hide');
        })
    })
</script>