<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?= DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
    
        <div class="row-fluid">
            <div class="span6">
                <?= DwForm::date('audit', array('class'=>'input-required mask-date input-date show-errors'), date("Y-m-d"), 'Día'); ?>
            </div>            
        </div>
    
        <div class="row-fluid">
            <div class="form-actions">
                <?= DwButton::submit('Listar auditorías', 'check', NULL, 'mostrar'); ?>                
                <?= DwButton::cancel(); ?>
            </div>
        </div>
        
    
    <?= DwForm::close(); ?>
        
    
</div>