<?php echo Tag::js('jquery/ui/jquery.ui.widget'); ?>
<?php echo Tag::js('jquery/jquery-file-upload/jquery.iframe-transport'); ?>
<?php echo Tag::js('jquery/jquery-file-upload/jquery.fileupload'); ?>
<?php echo Tag::js('jquery/jquery-file-upload/jquery.fileupload-fp'); ?>
<?php echo Tag::js('jquery/jquery-file-upload/jquery.fileupload-ui'); ?>
<!--[if gte IE 8]><?php echo Tag::js('jquery/jquery-file-upload/cors/jquery.xdr-transport'); ?><![endif]-->