<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::date('log', array('class'=>'input-required mask-date input-date show-errors'), date("Y-m-d"), 'Día'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::submit('Listar logs', 'check', NULL, 'mostrar'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>


    <?php echo DwForm::close(); ?>


</div>