<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?= DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        
        <div class="row-fluid">
            <div class="span4">
                <?= DwForm::text('menu.menu', array('class'=>'input-required mask-alphanum show-error'), $menu->menu, 'Título'); ?>
            </div>
            <div class="span4">
                <?= DwForm::dbSelect('menu.menu_id', 'menu', array('sistema/menu', 'getListadoMenu', Menu::ACTIVO), 'Ninguno', array('class'=>'mask-pint show-errors'), $menu->menu_id, 'Menú padre'); ?>
            </div>
            <div class="span4">
                <?= DwForm::dbSelect('menu.recurso_id', 'recurso', array('sistema/recurso', 'getListadoRecurso', Recurso::ACTIVO), NULL, array('class'=>'mask-pint show-errors'), $menu->recurso_id, 'Recurso'); ?>
            </div>            
        </div>
        <div class="row-fluid">
            <div class="span4">
                <?= DwForm::text('menu.posicion', array('class'=>'mask-pint show-error'), $menu->posicion, 'Posición'); ?>
            </div>
            <div class="span4">
                <?= DwForm::text('menu.icono', array('class'=>'mask-alphanum show-error'), $menu->icono, 'Icono a mostrar'); ?>
            </div>
            <div class="span4">
                <?= DwForm::text('menu.url', array('class'=>'show-error'), $menu->url, 'URL'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <?= DwForm::select('menu.visibilidad', array(Menu::BACKEND=>'Backend', Menu::FRONTEND=>'Frontend'), array('class'=>'input-required show-errors'), $menu->visibilidad, 'Visibilidad'); ?>
            </div>
            <?= DwForm::hiddenKey('menu.id', $menu->id)?>        
        </div>            
    
        <div class="row-fluid">
            <div class="form-actions">
                <?= DwButton::save('Guardar menu'); ?>
                <?= DwButton::reset('form'); ?>
                <?= DwButton::cancel('sistema/menu/listar/'); ?>
            </div>
        </div>
    
    <?= DwForm::close(); ?>
    
</div>
