<?php View::notify(); ?>

<script type="text/javascript">
    var ciudades = <?php echo $ciudades; ?>;
    $(function() {
        $('#ciudad').typeahead({
                source: ciudades, items:5
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('sucursal.sucursal', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), $sucursal->sucursal, 'Nombre de la sucursal'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span6">
                <?php echo DwForm::text('sucursal.direccion', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error'), $sucursal->direccion, 'Dirección'); ?>
            </div>
            <div class="span6">
                <?php echo DwForm::text('ciudad', array('class'=>'input-xxlarge input-required input-alphanum mask-alphanum show-error', 'autocomplete'=>'off'), $sucursal->ciudad, 'Ciudad'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::tel('sucursal.celular', array('class'=>'input-numeric mask-pint show-error'), $sucursal->celular, 'Celular'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::tel('sucursal.telefono', array('class'=>'input-numeric mask-pint show-error'), $sucursal->telefono, 'Teléfono'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::tel('sucursal.fax', array('class'=>'input-numeric mask-pint show-error'), $sucursal->fax, 'Fax'); ?>
            </div>

            <?php echo DwForm::hiddenKey('sucursal.id', $sucursal->id); ?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar sucursal'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>