<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"config/sucursal/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("config/sucursal/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <th class="col-collapse" data-search="direccion">DIRECCION</th>
                    <th class="col-collapse" data-search="ciudad">CIUDAD</th>
                    <th class="col-collapse" data-search="celular">CELULAR</th>
                    <th class="col-collapse" data-search="telefono">TELEFONO</th>
                    <th class="col-collapse" data-search="fax">FAX</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($sucursales->items as $sucursal): ?>
                    <?php $key_upd = DwSecurity::getKey($sucursal->id, 'upd_sucursal'); ?>
                    <?php $key_del = DwSecurity::getKey($sucursal->id, 'del_sucursal'); ?>
                    <tr>
                        <td><?php echo $sucursales->counter; ?></td>
                        <td><?php echo $sucursal->sucursal; ?></td>
                        <td><?php echo $sucursal->direccion; ?></td>
                        <td><?php echo $sucursal->ciudad; ?></td>
                        <td><?php echo $sucursal->celular; ?></td>
                        <td><?php echo $sucursal->telefono; ?></td>
                        <td><?php echo $sucursal->fax; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar sucursal', "config/sucursal/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php echo DwHtml::buttonTable('Eliminar sucursal', "config/sucursal/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar sucursal', 'confirm-body'=>'Está seguro de eliminar esta sucursal? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'ban-circle'); ?>
                        </td>
                    </tr>
                    <?php $sucursal->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$sucursales, 'url'=>"config/sucursal/listar/$order/")); ?>

</div>