<?php View::notify(); ?>

<?php $old_privilegios = array(); ?>

<script type="text/javascript">  
    $(function() {
        $('table').dwGrid({             
            form_search: false,
            order_attr: '<?= (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"sistema/privilegio/listar/"
        });
    });    
</script>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?= DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>            
    
        <div class="dw-overflow">
    
            <table class="table table-bordered table-hover table-striped table-condensed" style="min-width: 1900px;">        
                <thead>
                    <tr>                
                        <th rowspan="2" class="no-responsive dw-text-middle">RECURSO</th>
                        <th rowspan="2" class="no-responsive col-collapse dw-text-middle">DESCRIPCION</th>
                        <th colspan="<?= count($perfiles); ?>"class="no-responsive dw-text-center">PERFILES</th>
                    </tr>
                    <tr>
                        <?php foreach($perfiles as $perfil) { ?>
                        <th class="no-responsive dw-text-center"><?= $perfil->perfil; ?></th>
                        <?php } ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($recursos->items as $recurso) : ?>
                    <tr>
                        <td><?= $recurso->recurso; ?></td>
                        <td><?= $recurso->descripcion; ?></td>
                        <?php foreach ($perfiles as $perfil) : ?>
                            <?php if (in_array("$recurso->id-$perfil->id", $privilegios)) { ?>                            
                                <td>                            
                                    <?php $old_privilegios[] = $recurso->id.'-'.$perfil->id ?>
                                    <?= DwForm::check('privilegios[]', $recurso->id.'-'.$perfil->id, NULL, TRUE); ?>
                                </td>
                            <?php } else { ?>
                                <td>                            
                                    <?= DwForm::check('privilegios[]', $recurso->id.'-'.$perfil->id); ?>
                                </td>            
                            <?php } ?>
                        <?php endforeach ?>
                    </tr>
                    <?php endforeach; ?>
                </tbody>

            </table>
        
        </div>
        
        <?= DwForm::hidden('old_privilegios', null, join(',', $old_privilegios)); ?>
        <div class="row-fluid">
            <div class="form-actions">
                <?= DwButton::save('Guardar privilegios'); ?>          
                <?= DwButton::cancel(); ?>
            </div>
        </div>
    
    <?php DwForm::close() ;?>
    
    <?php View::partial('paginators/default', false, array('page'=>$recursos, 'url'=>"sistema/privilegio/listar/$order/")); ?>
    
</div>