<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>
            <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
            <li><a href="#tab2" data-toggle="tab">Información de la cuenta</a></li>
            <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
        </ul>
        <div class="tab-content">

            <div class="tab-pane active" id="tab1">

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('persona.nombre', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), $usuario->nombre, 'Nombre'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::text('persona.apellido', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), $usuario->apellido, 'Apellido'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::number('persona.nuip', array('class'=>'input-xxlarge input-required mask-pint show-error'), $usuario->nuip, 'Nuip'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::dbSelect('persona.tipo_nuip_id', 'tipo_nuip', array('params/tipo_nuip', 'getListadoTipoNuip'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), $usuario->tipo_nuip_id, 'Tipo de identificación'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::email('usuario.email', array('class'=>'input-xxlarge mask-email show-error'), $usuario->email, 'Email'); ?>
                    </div>
                </div>

            </div>

            <div class="tab-pane" id="tab2">

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::text('usuario.login', array('class'=>'input-xxlarge readonly'), $usuario->login, 'Usuario'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::oneSelect('usuario.perfil_id', $usuario->perfil, array('class'=>'input-xxlarge readonly'), 'Perfil'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::select('usuario.app_ajax', array('1'=>'On', '0'=>'Off'), array('class'=>'input-list input-required input-xxlarge'), $usuario->app_ajax, 'App con AJAX', 'Deshabilitar para conexiones lentas'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::select('usuario.tema', $temas, array('class'=>'input-list input-required input-xxlarge'), $usuario->tema, 'Apariencia'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::number('usuario.datagrid', array('class'=>'input-numeric show-error input-required'), $usuario->datagrid, 'Cantidad de datos por página', 'Esta información se utiliza en los listados de informaciones y reportes'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::pass('oldpassword', array('class'=>'input-xxlarge show-error'), '', 'Contraseña anterior'); ?>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span6">
                        <?php echo DwForm::pass('usuario.password', array('class'=>'input-xxlarge input-pass show-error'), '', 'Contraseña'); ?>
                    </div>
                    <div class="span6">
                        <?php echo DwForm::pass('repassword', array('class'=>'input-xxlarge input-repass show-error'), '', 'Confirmación'); ?>
                    </div>
                </div>

            </div>

            <div class="tab-pane" id="tab3">

                <div class="row-fluid fileupload-buttonbar">

                    <div class="span6" style="margin-bottom: 20px;">

                        <div class="row-fluid">

                            <div class="span6">
                                <div class="span12">
                                    <span class="btn btn-success fileinput-button">
                                        <i class="icon-plus icon-white"></i> <span>Fotografía...</span>
                                        <input id="fotografia" type="file" name="fotografia" class="input-large input-upload">
                                    </span>
                                </div>

                                <div class="span12" style="margin-left: 0px;">
                                    <div id="upload-progress" class="fileupload-progress fade">
                                        <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="margin-top: 5px;">
                                            <div class="bar" style="width:0%;"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="span6">
                                <div class="dw-picture-profile dw-text-center dw-text-middle dw-shadow-dark" style="margin: 5px auto 0px;">
                                    <?php echo DwHtml::img("upload/personas/$usuario->fotografia", "$usuario->nombre $usuario->apellido", array('id'=>'img-persona')); ?>
                                </div>
                            </div>

                        </div>

                    </div>

                </div>

                <?php echo DwForm::hidden('persona.fotografia', NULL, $usuario->fotografia); ?>
                <?php echo DwForm::hiddenKey('usuario.id', $usuario->id); ?>
            </div>

            <div class="row-fluid">
                <div class="form-actions">
                    <?php echo DwButton::save('Actualizar mis datos'); ?>
                    <?php echo DwButton::reset('form'); ?>
                    <?php echo DwButton::cancel(); ?>
                </div>
            </div>

        </div>

    <?php echo DwForm::close(); ?>

</div>

<?php View::partial('jquery.file-upload'); ?>

<script type="text/javascript">

    $('#fotografia').fileupload({
        url: '<?php echo PUBLIC_PATH; ?>sistema/mi_cuenta/upload/',
        dataType: 'json',
        maxFileSize: 3000000, //2MB
        acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
        start: function() {
            $("#dw-message").empty();
            $('#upload-progress').removeClass('fade');
            $('.bar').parent().removeClass('progress-danger').addClass('progress-success');
            $('[type=submit]').attr('disabled', 'disabled');
        },
        progress: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('.bar').css('width',progress + '%');
        },
        add: function (e, data) {
            var jqXHR = data.submit()
            .done(function (result, textStatus, jqXHR) {
                if(textStatus!='success' || result.error!=null) {
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+(result.error!=null) ? result.error : textStatus);
                } else {
                    DwMessage('El archivo se ha cargado correctamente!', 'success');
                    $("#persona_fotografia").val(result.name);
                    $("#img-persona").attr('src', '<?php echo PUBLIC_PATH; ?>img/upload/personas/'+result.name);
                }
            })
            .fail(function (jqXHR, textStatus, errorThrown) {
                if(textStatus!=null){
                    DwMessage('Oops! el archivo no se ha podido cargar. <br />Detalle del error: '+textStatus);
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    setTimeout(function() { $('#upload-progress').addClass('fade'); }, 1000);
                } else {
                    DwMessage('Oops! al parecer el archivo no es una imágen válida. <br />Intenta con otro archivo.');
                    $('.bar').parent().removeClass('progress-success').addClass('progress-danger');
                    $('#upload-progress').addClass('fade');
                }
            })
            .always(function () {
                setTimeout(function() { $('#upload-progress').addClass('fade'); $('.bar').css('width','0%'); }, 1000);
                $('[type=submit]').removeAttr('disabled');
            });
        }
    });
</script>

