<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?= DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
    
     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>        
            <li class="active"><a href="#tab1" data-toggle="tab">Información personal</a></li>
            <li><a href="#tab2" data-toggle="tab">Información de la cuenta</a></li>
            <li><a href="#tab3" data-toggle="tab">Cargar imágen</a></li>
        </ul>
        <div class="tab-content">
            
            <div class="tab-pane active" id="tab1">
    
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::text('persona.nombre', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), $usuario->nombre, 'Nombre'); ?>
                    </div>
                    <div class="span6">
                        <?= DwForm::text('persona.apellido', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), $usuario->apellido, 'Apellido'); ?>
                    </div>            
                </div>    
    
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::number('persona.nuip', array('class'=>'input-xxlarge input-required mask-pint show-error'), $usuario->nuip, 'Nuip'); ?>
                    </div>
                    <div class="span6">
                        <?= DwForm::dbSelect('persona.tipo_nuip_id', 'tipo_nuip', array('params/tipo_nuip', 'getListadoTipoNuip'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), $usuario->tipo_nuip_id, 'Tipo de identificación'); ?>
                    </div>            
                </div>
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::email('usuario.email', array('class'=>'input-xxlarge mask-email show-error'), $usuario->email, 'Email'); ?>
                    </div>                    
                </div>               
                
            </div>
            
            <div class="tab-pane" id="tab2">
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::text('usuario.login', array('class'=>'input-xxlarge readonly'), $usuario->login, 'Usuario'); ?>
                    </div>
                    <div class="span6">
                        <?= DwForm::dbSelect('usuario.perfil_id', 'perfil', array('sistema/perfil', 'getListadoPerfil', 'mi_cuenta'), NULL, array('class'=>'input-xxlarge input-required input-list show-errors'), $usuario->perfil_id, 'Perfil'); ?>
                    </div>
                </div>   
                
                <?php if(APP_OFFICE) { ?>
                <div class="row-fluid">                                        
                    <div class="span6">
                        <?= DwForm::dbSelect('usuario.sucursal_id', array('sucursal', 'ciudad'), array('config/sucursal', 'getListadoSucursal'), array('todas'=>'Todas'), array('class'=>'input-xxlarge input-required mask-pint show-errors'), empty($usuario->sucursal_id) ? 'todas' : $usuario->sucursal_id, 'Sucursal'); ?>
                    </div>                    
                </div>
                <?php } ?>
                
                <div class="row-fluid">                                        
                    <div class="span6">
                        <?= DwForm::select('usuario.app_ajax', array('1'=>'On', '0'=>'Off'), array('class'=>'input-list input-required input-xxlarge'), $usuario->app_ajax, 'App con AJAX', 'Deshabilitar para conexiones lentas'); ?>
                    </div>                    
                    <div class="span6">
                        <?= DwForm::select('usuario.tema', $temas, array('class'=>'input-list input-required input-xxlarge'), $usuario->tema, 'Apariencia'); ?>
                    </div>                    
                </div>
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::pass('oldpassword', array('class'=>'input-xxlarge show-error'), '', 'Contraseña anterior'); ?>
                    </div>                    
                </div>
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::pass('usuario.password', array('class'=>'input-xxlarge input-pass show-error'), '', 'Contraseña'); ?>
                    </div>
                    <div class="span6">
                        <?= DwForm::pass('repassword', array('class'=>'input-xxlarge input-repass show-error'), '', 'Confirmación'); ?>
                    </div>            
                </div>
                   
            </div>
            
            <div class="tab-pane" id="tab3">
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::file('fotografia', array('class'=>'input-xxlarge'), 'Fotografía', 'Formatos permitidos: GIF, JPG, PNG'); ?>
                    </div>
                    
                    <div class="span6 hidden-phone dw-text-right">
                        <div class="span5 dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">
                            <?= DwHtml::img("upload/personas/$usuario->fotografia", "$usuario->nombre $usuario->apellido"); ?>
                        </div>                        
                    </div>
                    
                </div>   
                <?= DwForm::hiddenKey('usuario.id', $usuario->id); ?>
            </div>
            
            <div class="row-fluid">
                <div class="form-actions">
                    <?= DwButton::save('Actualizar mis datos'); ?>
                    <?= DwButton::reset('form'); ?>
                    <?= DwButton::cancel(); ?>
                </div>
            </div>
            
        </div>
    
    <?= DwForm::close(); ?>
    
</div>
