<div class="navbar navbar-fixed-top user-nav">	
    <div class="navbar-inner">		
        <div class="container">			                    			
            <?php echo DwHtml::link('principal', '<i class="icon-globe icon-expand"></i>'.APP_NAME, array('class'=>'brand'), '', FALSE); ?>                    
            <div class="pull-right">

            </div>                    
        </div>                                
    </div>
</div>