<div class="navbar navbar-fixed-top user-nav">
    <div class="navbar-inner">
        <div class="container">
            <?php echo DwHtml::link('dashboard', DwHtml::img("upload/empresa/".APP_CLIENT_LOGO, APP_NAME, array('style'=>'height: 40px;')), '' , FALSE); ?>
            <button class="btn btn-navbar btn-list-phone" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="pull-right">
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon-user"></i> <?php echo Session::get('login'); ?> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><?php echo DwHtml::link('sistema/mi_cuenta/', 'Perfil'); ?></li>
                            <li class="divider"></li>
                            <li><?php echo DwHtml::link('sistema/login/salir', 'Salir', array('class'=>'no-load'), 'icon-off', FALSE); ?></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>

        <div class="hidden-desktop">
            <div class="nav-collapse nav-list-phone">
                <?php echo DwMenu::phone(); ?>
            </div>
        </div><!-- fin contenedor menú-->
    </div>
</div>