<!DOCTYPE html>
<html lang="es">
    <head>
        <title><?php echo $page_title; ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?php echo APP_CHARSET; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">                      
        <?php Tag::css('bootstrap/default/css/bootstrap.min'); ?>        
        <?php Tag::css('font-awesome.min'); ?>                
        <?php Tag::css('base'); ?>
        <?php Tag::css('style'); ?>
        <?php Tag::css('themes/default'); ?>        
        <?php echo Html::includeCss(); ?>
        <?php if(!APP_LOCAL) { ?>
            <link href="http://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet" type="text/css">
        <?php } ?>
        <style type="text/css">                    
            
        </style>     
        <?php echo Tag::js('jquery/jquery.min').PHP_EOL; ?>        
        
    </head>
    <body>
        
        <div id="dw-shell-load">             
            <div id="dw-console" class="container"></div>            
            <div id="dw-shell-content" class="container-fluid"> 
                <noscript><h5 style="text-align: center;">¡Tu navegador no soporta Javascript!.. Activa el uso de Javascript en tu navegador.</h5><meta http-equiv="refresh" content="1; URL=<?php echo PUBLIC_PATH; ?>sistema/login/salir/no-script/" /></noscript>
                <?php View::content(); ?>                                                         
            </div>                        
        </div>
                               
    </body>
</html>
