<!DOCTYPE html>
<html lang="es">
    <head>
        <title><?php echo $page_title; ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?php echo APP_CHARSET; ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php Tag::css('bootstrap/default/css/bootstrap.min'); ?>
        <?php Tag::css('font-awesome.min'); ?>
        <!--[if IE 7]>
            <link rel="stylesheet" href="<?php echo PUBLIC_PATH; ?>css/font-awesome-ie7.min.css">
        <![endif]-->
        <?php Tag::css('style'); ?>
        <?php Tag::css('backend/base'); ?>
        <?php Tag::css('backend/style'); ?>
        <?php Tag::css('backend/login'); ?>
        <?php Tag::css('backend/themes/default/default'); ?>
        <?php echo Html::includeCss(); ?>
        <?php if(!APP_LOCAL) { ?>
            <link href="http://fonts.googleapis.com/css?family=Play:400,700" rel="stylesheet" type="text/css">
        <?php } ?>

        <?php echo Tag::js('jquery/jquery.min').PHP_EOL; ?>

    </head>
    <body>

        <?php View::partial('backend/header_login'); ?>

        <div id="dw-shell-load">
            <div id="dw-shell-content" class="container-fluid">

                <?php View::notify(); ?>

                <div class="container-fluid dw-shell-view">
                    <div class="row-fluid" style="margin-top: 200px">
                        <div class="span4 dw-text-center">
                            <br />
                            <i class="icon-cogs" style="font-size: 150px;"></i>
                        </div>
                        <div class="span8 dw-text-left">
                            <h1>En estos momentos estamos en proceso de mantenimiento.</h1>
                            <br />
                            <br />
                            <h1>Por favor ingresa dentro de  <?php echo APP_UPDATE_TIME; ?>.</h1>
                        </div>
                    </div>

                </div>

            </div>
        </div>

        <?php View::partial('backend/footer'); ?>

    </body>

</html>
