<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            form_search: true,
            form_action: '<?php echo PUBLIC_PATH; ?>sistema/usuario/buscar/',
            form_load_data : 'dw-shell-content',
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"sistema/usuario/buscar/<?php echo $field.'/'.$value.'/'; ?>"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("sistema/usuario/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
            <?php echo DwHtml::button("sistema/usuario/listar/", 'listar', array('class'=>'btn-warning'), 'ok', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow" id="data-result">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="login">LOGIN</th>
                    <th class="col-collapse" data-search="nombre">NOMBRE</th>
                    <th class="col-collapse" data-search="apellido">APELLIDO</th>
                    <th class="col-collapse" data-search="email">EMAIL</th>
                    <th class="col-collapse" data-search="perfil">PERFIL</th>
                    <?if(APP_OFFICE) { //Si está activa la opción de oficinas ?>
                    <th class="col-collapse" data-search="sucursal">SUCURSAL</th>
                    <? } ?>
                    <th class="col-collapse" data-search="estado_usuario">ESTADO</th>
                    <th class="btn-actions no-responsive" style="width: 100px;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php if($usuarios) { ?>
                <?php foreach($usuarios->items as $usuario): ?>
                    <?php $key_upd = DwSecurity::getKey($usuario->id, 'upd_usuario'); ?>
                    <?php $key_ina = DwSecurity::getKey($usuario->id, 'bloquear_usuario'); ?>
                    <?php $key_rea = DwSecurity::getKey($usuario->id, 'reactivar_usuario'); ?>
                    <tr>
                        <td><?php echo $usuarios->counter; ?></td>
                        <td><?php echo ($field=='login') ? DwUtils::resaltar($value, $usuario->login) : $usuario->login; ?></td>
                        <td><?php echo ($field=='nombre') ? DwUtils::resaltar($value, $usuario->nombre) : $usuario->nombre; ?></td>
                        <td><?php echo ($field=='apellido') ? DwUtils::resaltar($value, $usuario->apellido) : $usuario->apellido; ?></td>
                        <td><?php echo ($field=='email') ? DwUtils::resaltar($value, $usuario->email) : $usuario->email; ?></td>
                        <td><?php echo ($field=='perfil') ? DwUtils::resaltar($value, $usuario->perfil) : $usuario->perfil; ?></td>
                        <?if(APP_OFFICE) { //Si está activa la opción de oficinas ?>
                        <td><?php echo empty($usuario->sucursal) ? ( ($value=='todas' ) ? DwUtils::resaltar($value, 'Todas') : 'Todas') : DwUtils::resaltar($value, $usuario->sucursal); ?></td>
                        <? } ?>
                        <td><?php echo ($usuario->estado_usuario == EstadoUsuario::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Bloqueado</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Modificar usuario', "sistema/usuario/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php if($usuario->estado_usuario == EstadoUsuario::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Bloquear usuario', "sistema/usuario/estado/bloquear/$key_ina/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar usuario', "sistema/usuario/estado/reactivar/$key_rea/", null, 'danger', 'flag'); ?>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php $usuarios->counter++; ?>
                <?php endforeach; ?>
            </tbody>
            <?php } ?>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$usuarios, 'url'=>"sistema/usuario/buscar/$field/$value/$order/")); ?>

</div>