<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="dw-overflow">

        <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span12">
                <?php echo DwForm::textarea('estado_usuario.descripcion', array('class'=>'input-xxlarge input-required mask-text show-error'), NULL, 'Motivo del cambio de estado'); ?>
            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Actualizar estado'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>

        <?php echo DwForm::close(); ?>

    </div>

</div>
