<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("sistema/configuracion/", 'basic', array('class'=>'btn-success active'), 'asterisk', APP_AJAX); ?>
            <?php echo DwHtml::button("sistema/configuracion/routes/", 'routes', array('class'=>'btn-warning'), 'random', APP_AJAX); ?>
            <?php echo DwHtml::button("sistema/configuracion/databases/", 'databases', array('class'=>'btn-warning'), 'hdd', APP_AJAX); ?>
            <div class="pull-right">
                <?php echo DwHtml::button("sistema/configuracion/reset/", 'reset', array('class'=>'btn-danger js-confirm', 'confirm-title'=>'Restarurar archivos de configuración', 'confirm-body'=>'Está seguro de querer restastaurar los archivos de configuración? <br />Recuerda que esta operación no se puede reversar.'), 'warning-sign', APP_AJAX); ?>
            </div>
        </div>
    </div>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate', 'style-form'=>'form-horizontal')); ?>

        <div class="row-fluid">
            <div class="span1">&nbsp;</div>

            <div class="span4">

                <?php echo DwForm::fieldset("Configuración de la aplicación"); ?>

                    <?php echo DwForm::text('application.name', array('class'=>'input-required show-error'), $config['application']['name'], 'Nombre del proyecto:'); ?>

                    <?php echo DwForm::text('application.timezone', array('class'=>'input-required show-error'), $config['application']['timezone'], 'Timezone:'); ?>

                    <?php echo DwForm::select('application.production', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required show-error'), $config['application']['production'], 'Proyecto en producción:'); ?>

                    <?php echo DwForm::select('application.database', array('development'=>'Development', 'production'=>'Production'), array('class'=>'input-required show-error'), $config['application']['database'], 'Entorno de conexión:'); ?>

                    <?php echo DwForm::text('application.dbdate', array('class'=>'input-required show-error'), $config['application']['dbdate'], 'Formato de fechas:'); ?>

                    <?php echo DwForm::select('application.debug', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required show-error'), $config['application']['debug'], 'Debug:'); ?>

                    <?php echo DwForm::select('application.log_exceptions', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required show-error'), $config['application']['log_exceptions'], 'Mostrar excepciones:'); ?>

                    <?php echo DwForm::text('application.charset', array('class'=>'input-required show-error'), $config['application']['charset'], 'Juego de caracteres:'); ?>

                    <?php echo DwForm::text('application.cache_driver', array('class'=>'input-required show-error'), $config['application']['cache_driver'], 'Driver de caché:'); ?>

                    <?php echo DwForm::hidden('application.metadata_lifetime', null, $config['application']['metadata_lifetime']); ?>

                    <?php echo DwForm::hidden('application.namespace_auth', null, $config['application']['namespace_auth']); ?>

                    <?php echo DwForm::select('application.routes', array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required show-error'), $config['application']['routes'], 'Habilitar el routes:'); ?>

                <?php echo DwForm::fieldset(); ?>

            </div>

            <div class="span1">&nbsp;</div>

            <div class="span4">
                <?php echo DwForm::fieldset("<a id='add-config' href='#form-add-config' class='btn' data-toggle='modal'><i class='icon-ok icon-expand'></i>Agregar parámetro</a>"); ?>
                <?php if(isset($config['custom'])) { ?>
                    <?php foreach($config['custom'] as $campo => $valor): ?>
                        <?php
                        switch ($campo) {
                            case 'app_update':      $text = 'Sistema en actualización';
                                                    break;
                            case 'app_update_time': $text = 'Tiempo de la actualización';
                                                    break;
                            case 'app_version':     $text = 'Versión de la aplicación';
                                                    break;
                            case 'app_logger':      $text = 'Generar logs de la base de datos';
                                                    break;
                            case 'app_office':      $text = 'Manejo de sucursales de la empresa';
                                                    break;
                            case 'app_ajax':        $text = 'Cargar con AJAX';
                                                    break;
                            case 'app_local':       $text = 'La aplicación se encuentra en el localhost';
                                                    break;
                            case 'login_exclusion': $text = 'Nombre de usuarios excluidos';
                                                    break;
                            case 'datagrid':        $text = 'Cantidad de datos por página en los reportes';
                                                    break;
                            default:                $text = $campo;
                                                    break;
                        }
                        ?>
                        <?php if ( in_array($valor , array('On', 'Off')) ) {  ?>
                            <?php echo DwForm::select("custom.$campo", array('Off'=>'No', 'On'=>'Si'), array('class'=>'input-required show-error'), $valor, ucfirst($text)); ?>
                        <?php } else { ?>
                            <?php echo DwForm::text("custom.$campo", array('class'=>'input-required show-error'), $valor, ucfirst($text)); ?>
                        <?php } ?>
                    <?php endforeach; ?>
                <?php } ?>

                <div id="append-config"></div>
                <p>Los campos creados se definirán automáticamente al cargar el aplicativo y se almacenarán en el config.ini</p>
                <p>Para eliminar una variable puede colocar el valor "delete-var" en el input.</p>

                <?php echo DwForm::fieldset(); ?>

            </div>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::submit('Guardar configuración', 'check'); ?>
                <?php echo DwButton::cancel(); ?>
            </div>
        </div>


    <?php echo DwForm::close(); ?>


</div>

<?php echo DwForm::open('', '', array('id'=>'form-modal', 'class'=>'dw-validate', 'style'=>'form-horizontal')); ?>
    <div class="modal hide" id="form-add-config">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Agregar variable de configuración</h3>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="span5">
                    <?php echo DwForm::text('variable', array('class'=>'input-required show-error'), null, 'Nombre de la variable'); ?>
                </div>
                <div class="span5">
                    <?php echo DwForm::text('valor', array('class'=>'input-required show-error'), null, 'Valor'); ?>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
            <?php echo DwForm::submit("Crear", array('class'=>'btn btn-primary')); ?>
        </div>
    </div>
<?php echo DwForm::close(); ?>

<script type="text/javascript">
    $(function(){
        $("#form-modal").submit(function(){
            if(validForm($(this).attr('name'), false)) {
                variable = $('#variable');
                valor = $("#valor");
                $('<div class="control-group">'+
                '<label for="custom_'+variable.val()+'" class="control-label">'+variable.val()+':<span class="req">*</span></label>'+
                '<div class="controls">'+
                '<input id="custom_'+variable.val()+'" class="field text input-required show-errors" type="text" value="'+valor.val()+'" name="custom['+variable.val()+']">'+
                '<p class="help-block"> </p>'+
                '</div></div>').appendTo('#append-config');
                variable.attr('value', '');
                valor.attr('value', '');
                DwSpinner('hide');
                $("#form-add-config").modal('hide');
            }
            return false;
        });
    });
</script>