<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?= DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
        
        <div class="row-fluid">
            <div class="span4">
                <?= DwForm::text('recurso.modulo', array('class'=>'mask-alphanum show-error'), $recurso->modulo, 'Módulo'); ?>
            </div>
            <div class="span4">
                <?= DwForm::text('recurso.controlador', array('class'=>'required mask-alphanum show-error'), $recurso->controlador, 'Controlador'); ?>
            </div>
            <div class="span4">
                <?= DwForm::text('recurso.accion', array('class'=>'mask-alphanum show-error'), $recurso->accion, 'Acción'); ?>
            </div>
        </div>    
        <div class="row-fluid">
            <div class="span12">
                <?= DwForm::textarea('recurso.descripcion', array('class'=>'required mask-text show-error input-xxlarge'), $recurso->descripcion, 'Descripción'); ?>
            </div>            
            <?= DwForm::hiddenKey('recurso.id', $recurso->id)?>
        </div>           
    
        <div class="row-fluid">
            <div class="form-actions">
                <?= DwButton::save('Guardar recurso'); ?>
                <?= DwButton::reset('form'); ?>
                <?= DwButton::cancel('sistema/recurso/listar/'); ?>
            </div>
        </div>
    
    <?= DwForm::close(); ?>
    
</div>
