<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>

        <div class="row-fluid">
            <div class="span4">
                <?php echo DwForm::text('recurso.modulo', array('class'=>'mask-alphanum show-error'), $recurso->modulo, 'Módulo'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('recurso.controlador', array('class'=>'input-required mask-alphanum show-error'), $recurso->controlador, 'Controlador'); ?>
            </div>
            <div class="span4">
                <?php echo DwForm::text('recurso.accion', array('class'=>'mask-alphanum show-error'), $recurso->accion, 'Acción'); ?>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <?php echo DwForm::textarea('recurso.descripcion', array('class'=>'input-required mask-text show-error input-xxlarge'), $recurso->descripcion, 'Descripción'); ?>
            </div>
            <?php echo DwForm::hiddenKey('recurso.id', $recurso->id)?>
        </div>

        <div class="row-fluid">
            <div class="form-actions">
                <?php echo DwButton::save('Guardar recurso'); ?>
                <?php echo DwButton::reset('form'); ?>
                <?php echo DwButton::cancel('sistema/recurso/listar/'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>
