<?php View::notify(); ?>
<style type="text/css">
    .tab-pane { min-height: 200px;}
</style>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?= DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
    
     <?php if(DESKTOP) { ?>
        <ul class="nav nav-tabs">
        <?php } else { ?>
        <ul class="nav nav-pills nav-stacked">
        <?php } ?>        
            <li class="active"><a href="#tab1" data-toggle="tab">Información general</a></li>            
            <li><a href="#tab2" data-toggle="tab">Cargar logo</a></li>
        </ul>
        <div class="tab-content">
            
            <div class="tab-pane active" id="tab1">
    
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::text('empresa.razon_social', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), NULL, 'Nombre o razón social'); ?>
                    </div>
                    <div class="span6">
                        <?= DwForm::text('empresa.siglas', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), NULL, 'Siglas o abrevación'); ?>
                    </div>            
                </div>    
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::text('empresa.nit', array('class'=>'input-xxlarge input-required mask-pint show-error'), NULL, 'Nit'); ?>
                    </div>
                    <div class="span6">
                        <?= DwForm::number('empresa.dv', array('class'=>'input-small input-required mask-pint show-error'), NULL, 'Dígito de verificación'); ?>
                    </div>            
                </div>
                
                <div class="row-fluid">
                    <div class="span12">
                        <?= DwForm::text('empresa.representante_legal', array('class'=>'input-xxlarge input-required mask-alphanum show-error'), NULL, 'Representante legal'); ?>
                    </div>
                </div> 
    
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::number('empresa.nuip', array('class'=>'input-xxlarge input-required mask-pint show-error'), NULL, 'Nuip'); ?>
                    </div>
                    <div class="span6">
                        <?= DwForm::dbSelect('empresa.tipo_nuip_id', 'tipo_nuip', array('params/tipo_nuip', 'getListadoTipoNuip'), NULL, array('class'=>'input-xxlarge input-required mask-pint show-errors'), NULL, 'Tipo de identificación'); ?>
                    </div>            
                </div>
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::url('empresa.pagina_web', array('class'=>'input-xxlarge show-error'), NULL, 'Página web'); ?>
                    </div>                    
                    <div class="span6">
                        <?= DwForm::email('empresa.email', array('class'=>'input-xxlarge mask-email show-error'), NULL, 'Email'); ?>
                    </div>                    
                </div>  
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::tel('empresa.telefono', array('class'=>'input-xxlarge mask-pint show-error'), NULL, 'Teléfono'); ?>
                    </div>
                    <div class="span6">
                        <?= DwForm::tel('empresa.fax', array('class'=>'input-xxlarge show-error'), NULL, 'Fax'); ?>
                    </div>            
                </div>
                
            </div>                        
            
            <div class="tab-pane" id="tab2">
                
                <div class="row-fluid">
                    <div class="span6">
                        <?= DwForm::file('logo', array('class'=>'input-xxlarge'), 'Logo', 'Formatos permitidos: GIF, JPG, PNG'); ?>
                    </div>
                    
                    <div class="span6 hidden-phone dw-text-right">
                        <div class="span5 dw-text-center dw-text-middle dw-shadow-dark" style="margin-top: 5px">                            
                            <?= DwHtml::img('upload/empresa/'.$empresa->logo, $empresa->razon_social); ?>                            
                        </div>                        
                    </div>
                    
                </div>   
                
                <?= DwForm::hiddenKey('empresa.id', $empresa->id); ?>
                
            </div>
            
            <div class="row-fluid">
                <div class="form-actions">
                    <?= DwButton::save('Guardar información'); ?>
                    <?= DwButton::reset('form'); ?>
                    <?= DwButton::cancel(); ?>
                </div>
            </div>
            
        </div>
    
    <?= DwForm::close(); ?>
    
</div>
