<?php View::notify(); ?>

<div class="container-fluid dw-shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <?= DwForm::open('', 'post', array('id'=>'form', 'class'=>'dw-validate')); ?>
    
        <div class="row-fluid">
            <div class="span6">
                <?= DwForm::text('perfil.perfil', array('class'=>'input-required mask-alpha show-error'), NULL, 'Perfil'); ?>
            </div>
            <div class="span6">
                <?= DwForm::text('perfil.plantilla', array('class'=>'mask-alphanum show-error'), NULL, 'Plantilla', 'La plantilla de sebe ubicar dentro la caperta "templates".'); ?>
            </div>
        </div>    
    
        <div class="row-fluid">
            <div class="form-actions">
                <?= DwButton::save('Guardar perfil'); ?>
                <?= DwButton::reset('form'); ?>
                <?= DwButton::cancel('sistema/perfil/listar/'); ?>
            </div>
        </div>
    
    <?= DwForm::close(); ?>
    
</div>
