<?php View::notify(); ?>

<script type="text/javascript">  
    $(function() {
        $('table').dwGrid({             
            form_search: false,
            order_attr: '<?= (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"sistema/perfil/listar/"
        });
    });    
</script>

<div class="container-fluid overflow">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <div class="btn-toolbar btn-toolbar-top">        
        <div class="btn-actions">            
            <?= DwHtml::button("sistema/perfil/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?> 
        </div>
    </div>
    
    <table class="table table-bordered table-hover table-striped table-condensed table-responsive">        
        <thead>
            <tr>
                <th>NUM</th>
                <th class="col-collapse" data-search="perfil">PERFIL</th>
                <th class="col-collapse" data-search="estado">ESTADO</th>
                <th class="btn-actions no-responsive">ACCIONES</th>
            </tr>            
        </thead>
        <tbody>            
            <?php foreach($perfiles->items as $perfil): ?>
                <?php $key_show = DwSecurity::getKey($perfil->id, 'show_perfil'); ?>                
                <?php $key_upd = DwSecurity::getKey($perfil->id, 'upd_perfil'); ?>
                <?php $key_del = DwSecurity::getKey($perfil->id, 'del_perfil'); ?>
                <tr>
                    <td><?= $perfiles->counter; ?></td>
                    <td><?= $perfil->perfil; ?></td>
                    <td><?= $perfil->estado; ?></td>
                    <td>                        
                        <?= DwHtml::buttonTable("sistema/perfil/ver/$key_show/", null, 'info', 'search'); ?>                        
                        <?= DwHtml::buttonTable("sistema/perfil/editar/$key_upd/", null, 'info', 'edit'); ?>
                        <?= DwHtml::buttonTable("sistema/perfil/eliminar/$key_del/", null, 'danger', 'remove'); ?>                        
                    </td>                    
                </tr>
                <?php $perfiles->counter++; ?>
            <?php endforeach; ?>
        </tbody>            
    </table> 
    
    <?php View::partial('paginators/default', false, array('page'=>$perfiles)); ?>
    
</div>