<?php View::notify(); ?>

<script type="text/javascript">
    $(function() {
        $('table').dwGrid({
            order_attr: '<?php echo (APP_AJAX) ? 'class="dw-ajax dw-spinner"' : ''; ?>',
            order_action: $.KumbiaPHP.publicPath+"sistema/perfil/listar/"
        });
    });
</script>

<div class="container-fluid dw-shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <div class="btn-toolbar btn-toolbar-top">
        <div class="btn-actions">
            <?php echo DwHtml::button("sistema/perfil/agregar/", 'agregar', array('class'=>'btn-success'), 'check', APP_AJAX); ?>
        </div>
    </div>

    <div class="dw-overflow">

        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th>NUM</th>
                    <th class="col-collapse" data-search="perfil">PERFIL</th>
                    <th class="col-collapse" data-search="plantilla">PLANTILLA</th>
                    <th class="col-collapse" data-search="usuarios">USUARIOS</th>
                    <th class="col-collapse" data-search="estado">ESTADO</th>
                    <th class="btn-actions no-responsive">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($perfiles->items as $perfil): ?>
                    <?php $key_show = DwSecurity::getKey($perfil->id, 'show_perfil'); ?>
                    <?php $key_upd = DwSecurity::getKey($perfil->id, 'upd_perfil'); ?>
                    <?php $key_inac = DwSecurity::getKey($perfil->id, 'inactivar_perfil'); ?>
                    <?php $key_reac = DwSecurity::getKey($perfil->id, 'reactivar_perfil'); ?>
                    <tr>
                        <td><?php echo $perfiles->counter; ?></td>
                        <td><?php echo $perfil->perfil; ?></td>
                        <td><?php echo $perfil->plantilla; ?></td>
                        <td><?php echo $perfil->usuarios; ?></td>
                        <td><?php echo ($perfil->estado == Perfil::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-important">Bloqueado</span>'; ; ?></td>
                        <td>
                            <?php echo DwHtml::buttonTable('Ver perfil', "sistema/perfil/ver/$key_show/", null, 'info', 'search'); ?>
                            <?php echo DwHtml::buttonTable('Modificar perfil', "sistema/perfil/editar/$key_upd/", null, 'info', 'edit'); ?>
                            <?php if($perfil->estado == Perfil::ACTIVO) { ?>
                                <?php echo DwHtml::buttonTable('Inactivar perfil', "sistema/perfil/estado/inactivar/$key_inac/", null, 'success', 'flag'); ?>
                            <?php } else { ?>
                                <?php echo DwHtml::buttonTable('Reactivar perfil', "sistema/perfil/estado/reactivar/$key_reac/", null, 'danger', 'flag'); ?>
                            <?php } ?>
                        </td>
                    </tr>
                    <?php $perfiles->counter++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>

    </div>

    <?php View::partial('paginators/default', false, array('page'=>$perfiles, 'url'=>"sistema/perfil/listar/$order/")); ?>

</div>